nama =str(input("Nama                   : "))
nim =int(input("NIM                    : "))
kelas=str(input("Kelas Paralel          : "))
ttl=input("Tempat/Tanggal Lahir   : ")
alamat=str(input("Alamat                 : "))
hobby=str(input("Hobby                  : "))
no=int(input("No. Hp                 : "))
print("\n           ---Biodata---\n")
print(f"Nama                   : {nama}\nNIM                    : {nim}\nKelas Paralel          : {kelas}\nTempat/Tanggal Lahir   : {ttl}\nAlamat                 : {alamat}\nHobby                  : {hobby}\nNo. Hp                 : {no}")
